include: package:lint/analysis_options.yaml

analyzer:
  errors:
    todo: warning
  exclude:
    - 'lib/generated/**'
    - 'lib/**.g.dart'
    - 'test/mock/mocks.mocks.dart'
linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: false
    prefer_double_quotes: false
    lines_longer_than_80_chars: false
    avoid_void_async: false
    constant_identifier_names: false
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    sort_pub_dependencies: false
    use_build_context_synchronously: false
