name: example
description: Test project to exercise Testable

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  gen_key:
    path: ../

dev_dependencies:
  build_runner:

flutter:
  uses-material-design: true