name: example
description: gen_keys example

version: 0.1.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gen_keys:
    path: ../

  cupertino_icons: ^1.0.5
  build_runner: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true