targets:
  $default:
    builders: 
      gen_keys|keys_file_builder:
        enabled: true

builders:
  gen_keys|keys_file_builder:
    import: 'package:gen_keys/keys_file_builder.dart'
    builder_factories: ['keysFileBuilder']
    build_extensions: { ".dart": [".keys.dart"] }
    auto_apply: dependents
    build_to: source
