name: gen_keys
description: Renamed to gen_keys
version: 0.1.0
repository: https://github.com/buttonsrtoys/gen_keys
issue_tracker: https://github.com/buttonsrtoys/gen_keys/issues

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^4.2.0
  build: ^2.3.0
  source_gen: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: false